### ISSUE TITLE
Mergin your code with dartx

### ISSUE THREAD

**Issue by shinayser** [jogboms/time.dart#10]
Hey @jogboms !

You work here is great! There is a library called dartx that has a proposal to add a lot of extensions to the dart's types. Since they were missing the time extensions I made a pull request to their repostory with your work.

I gave you credits on readme. Take a look and tell what you think: https://github.com/leisim/dartx/pull/11

**Comment by jogboms** [comment]
Following conversations from [leisim/dartx#11](leisim/dartx#11), I would be adding support for `int` and `double` conversions
