### ISSUE TITLE
[Feature Request]age calculation

### ISSUE THREAD

**Issue by shinriyo** [jogboms/time.dart#29]
Do you think about age calculation feature for it?
Converting DateTime birthday to int age.
`East Asian age reckoning` option also.

**Comment by jogboms** [comment]
Hey @shinriyo 

This is nice too. A PR?

**Comment by shinriyo** [comment]
@jogboms 

> This is nice too. A PR?

OK. Check it. Could you tell me how to make mock for DateTime?
https://github.com/jogboms/time.dart/pull/31

**Comment by jogboms** [comment]
Hey @shinriyo

Thanks for the PR. I dropped a review comment

**Comment by shinriyo** [comment]
I close.
