### ISSUE TITLE
Migrate to null-safety

### ISSUE THREAD

**Issue by TimWhiting** [jogboms/time.dart#37]
This package is currently blocking dartx from migrating to null-safety. Null-safety is now in beta, and the dart team is encouraging package authors to migrate now. I'll submit a pull request if you'd like to review it. I see there is one already open, but it doesn't bump the dart sdk min version to 2.12 like we are supposed to, and instead enables it in the analysis_options.yaml which is not required if you set the min sdk version properly.

**Comment by jogboms** [comment]
Hey @TimWhiting 
Thanks for the input. Released as 1.5.0-nullsafety.0
